### ISSUE TITLE
Gap Statistic

### ISSUE THREAD

**Issue by mepcotterell** [scalation/fda#2]
We need to implement and test the Gap statistic [1] for choosing the optimal k value (number of clusters) in K-Means.

### References
[1] Tibshirani, Robert, Guenther Walther, and Trevor Hastie. 2001. “Estimating the Number of Clusters in a Data Set via the Gap Statistic.” Journal of the Royal Statistical Society: Series B (Statistical Methodology) 63 (2). Blackwell Publishers Ltd.: 411–23. doi:10.1111/1467-9868.00293.

**Comment by mepcotterell** [comment]
@NBKlepp you can update us on your status with the Gap statistic code via this issue #2.

**Comment by NBKlepp** [comment]
I found something kind of confusing in the Tibshirani paper. If you look at section 4 where they actually compute the gap statistic they first have on page 415

"Results in the quantity

               s_{k} = root( ( 1 + 1/B ) sd_{k} ) ... "

At least that's what I think it says, because the square root sign doesn't extend past the first character of the expression...confusing...

Then later on in the paper they have 

"...          

               s_{k}=sd_{k}*root( 1 + 1/b )

That one is pretty clear. 

Which is it that we are supposed to use?

**Comment by mepcotterell** [comment]
I would suspect it's the latter. I found this article [1] that covers the Gap statistic, and it uses the latter (although it is referencing Tibshirani).

[1] https://datasciencelab.wordpress.com/2013/12/27/finding-the-k-in-k-means-clustering/

**Comment by NBKlepp** [comment]
Quick summary: 

The methods for computing the gap statistic for a particular set of data have all been implemented, and there is a short test object at the end of the KMeansClustering class which demonstrates the process of actually computing that gap statistic. It is an iterative process that requires lots of clustering to come to a best approximation of the gap statistic, and I'm not sure whether that should be implemented as a separate method inside of KMeansClustering or not. For now it is demonstrated inside of the gap statistic test object at the end of KMeansClustering. Originally I was worried that my gap statistic was always returning a value of k=1 is optimal number of clusters, however I realized yesterday that I was simply failing to actually call cl.cluster() to create the best cluster for the given data. After that it works smoothly as expected. This week I'll be using several different data sets on which to compute the estimated k-hat values for the optimal number of clusters, and I'll also be searching for gap statistic calculation packages in R to compare our implementation against.

**Comment by mepcotterell** [comment]
Awesome work, @NBKlepp! I look forward to seeing some "elbows" during our next meeting.

**Comment by mepcotterell** [comment]
@NBKlepp, in order order to implement the reference distribution according to method (b) in section 4 of Tibshirani et al. (so that it takes into account the shape of the original data), you can use the [`scalation.linalgebra.SVD`](https://github.com/scalation/fda/blob/master/scalation_1.2/src/main/scala/scalation/linalgebra/SVD.scala) class. This class is used to compute the Singular Value Decomposition (SVD) of a matrix using the Golub-Kahan-Reinsch algorithm. 

Given an m-by-n matrix `x`, you can perform SVD using the following code:
```scala
import scalation.linalgebra.SVD
val svd = new SVD (x)
val (u, s, vt) = svd.factor ()
val v = vt.t
```
This gives you the following:
 * `u`, an m-by-n `MatrixD` of left singular vectors
 * `s`, an n-length `VectorD` of singular values 
 * `v`, an n-by-n `MatrixD` of right singular vectors

If you have any questions about how to apply this to the generation of the reference distribution, then let me know. Good luck!

**Comment by mepcotterell** [comment]
@NBKlepp Any updates on this?

**Comment by mepcotterell** [comment]
@NBKlepp Please check over the [`GapStatistic`](https://github.com/scalation/fda/blob/master/scalation_1.3/scalation_modeling/src/main/scala/scalation/analytics/clusterer/GapStatistic.scala) object. We need to incorporate the use of multiple reference distributions as well as the standard deviation correction. Thanks!

**Comment by NBKlepp** [comment]
Can you please tell me how to test this code? I'm in the scalation_1.3/scalation_modeling directory, and I get the following error message when I run in sbt: 

`sbt.ResolveException: unresolved dependency: scalation#scalation_mathstat_2.12;1.3-SNAPSHOT: not found`

**Comment by NBKlepp** [comment]
New error message: 

```
[error] /Users/MacBot/Projects/FDA/fda/scalation_1.3/scalation_modeling/src/main/scala/scalation/analytics/clusterer/KMeansClustering.scala:545: object apache is not a member of package org
[error]     import org.apache.commons.math3.ml.clustering.KMeansPlusPlusClusterer
[error]                ^
[error] /Users/MacBot/Projects/FDA/fda/scalation_1.3/scalation_modeling/src/main/scala/scalation/analytics/clusterer/KMeansClustering.scala:560: not enough arguments for constructor KMeansPlusPlusClusterer: (x: scalation.linalgebra.MatrixD, k: Int, algo: scalation.analytics.clusterer.Algorithm.Algorithm, s: Int)scalation.analytics.clusterer.KMeansPlusPlusClusterer.
[error] Unspecified value parameter k.
[error]     val cl = new KMeansPlusPlusClusterer (k)
```

**Comment by NBKlepp** [comment]
Had to add apache as a library dependency. Fixed it as necessary. Gap statistic is working correctly with the newly incorporated multiple reference distribution and standard deviation difference. Closing this issue.
